/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Practica2;

import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author User
 */
public class ConvertidorDeTemperatura extends javax.swing.JFrame {

    /**
     * Creates new form ConvertidorDeTemperatura
     */
    public ConvertidorDeTemperatura() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        centigrados = new javax.swing.JTextField();
        fahrenheit = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setForeground(new java.awt.Color(255, 0, 153));
        jLabel1.setText("Centigrados");

        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setText("Fahrenheit");

        centigrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                centigradosActionPerformed(evt);
            }
        });
        centigrados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                centigradosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                centigradosKeyTyped(evt);
            }
        });

        fahrenheit.setEditable(false);
        fahrenheit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fahrenheitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(centigrados, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(fahrenheit))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(centigrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fahrenheit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void centigradosKeyTyped(java.awt.event.KeyEvent evt) {                                   
        char caracter = evt.getKeyChar();
        if ((caracter < '0')||(caracter > '9')) {
            if ((caracter!='.')&&(caracter!='-')){
                evt.consume();
            }
        }
    }  
    
    private void CentigradosFocusLost(java.awt.event.FocusEvent evt) {                                    
        if(validar(centigrados)==false){
            JOptionPane.showMessageDialog(this,centigrados.getText()+" Es un dato invalido","Dato Invalido",JOptionPane.WARNING_MESSAGE);
                centigrados.requestFocusInWindow();
                centigrados.selectAll();
        }else{
            centigrados.setText("");
        }
    }                                   

    private void FahrenheitFocusLost(java.awt.event.FocusEvent evt) {                                      
        if(validar(fahrenheit)==false){
            JOptionPane.showMessageDialog(this,fahrenheit.getText()+" Es un dato invalido","Dato Invalido",JOptionPane.WARNING_MESSAGE);
                fahrenheit.requestFocusInWindow();
                fahrenheit.selectAll();
        }else{
            fahrenheit.setText("");
        }
    }                                     

    private void CentigradosKeyReleased(java.awt.event.KeyEvent evt) {                                      
        if(validar(centigrados)==true){
            double numero = 0;
            double resultado = (numero*1.8)+(32);
            String grados = String.valueOf(Math.round(resultado*Math.pow(10,2))/Math.pow(10,2));
            fahrenheit.setText(grados);
        }else{
            fahrenheit.setText("");
        }
    }                                     

    private void FahrenheitKeyReleased(java.awt.event.KeyEvent evt) {                                        
        if(validar(fahrenheit)==true){
            int numero = 0;
            double resultado = (numero-32)/(1.8);
            String grados = String.valueOf(Math.round(resultado*Math.pow(10,2))/Math.pow(10,2));
            centigrados.setText(grados);
        }else{
            centigrados.setText("");
        }
    }                                   
    private void centigradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_centigradosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_centigradosActionPerformed

    private void fahrenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fahrenheitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fahrenheitActionPerformed

    private void centigradosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_centigradosKeyPressed
      
        // TODO add your handling code here:
    }//GEN-LAST:event_centigradosKeyPressed

    private void centigradosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_centigradosKeyTyped
       centigradosKeyTyped(evt);
    }          
    private boolean validar(JTextField oText){
        if(!oText.getText().isEmpty()){
            try{
                Double numero = Double.valueOf(oText.getText());
                return true;
            }catch(Exception e){
                return false;
            }
        }
        return true;
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_centigradosKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConvertidorDeTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConvertidorDeTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConvertidorDeTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConvertidorDeTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConvertidorDeTemperatura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField centigrados;
    private javax.swing.JTextField fahrenheit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
